### ISSUE TITLE
"app actions" vs. "client actions"?

### ISSUE THREAD

**Issue by data-henrik** [watson-developer-cloud/botkit-middleware#143] opened 2018-09-30 06:50 UTC
Watson Assistant supports client actions, indicating the app to perform actions. The examples for botkit-middleware seem to discuss a different kind of "app action". 

Clarification and a sample for both would be helpful.

**Comment by data-henrik** [comment] 2018-10-29 13:53
WA puts something like the following into its response object when a client action is encountered:

```
  "actions": [
    {
      "type": "client", 
      "name": "henriktest", 
      "parameters": {
        "input": {
          "text": "client test"
        }
      }, 
      "result_variable": "mydateOUT"
    }
  ], 

```

Ideally, botkit-middleware has a hook to react to this and is able to send back the result to WA.

**Comment by data-henrik** [comment] 2018-10-29 14:44
Would it be possible to expose `postMessage` to be able to send back the action result? In addition, maybe a new `processActions` hook  (before `after`) is needed to provide the necessary processing environment.

**Comment by Naktibalda** [comment] 2018-10-29 15:00
`Client actions` is a new functionality, this documentation was written long time ago.
You are welcome to implement and document it  yourself in this middleware or wait for @germanattanasio to do it.

There is no need to export `postMessage`, there is a `sendToWatson` method which takes care of context management too.

**Comment by data-henrik** [comment] 2018-10-29 15:09
@Naktibalda I have seen and worked with `sendToWatson`. My understanding is that it involves all the steps (before, after, etc.) again and it would introduce recursion. Basically, in the middle of processing `sendToWatson`, we call `sendToWatson` again.

**Comment by mitchmason** [comment] 2018-10-29 15:18
I haven't used this in awhile now...
but I think that if you want to use client side actions then instead you should use the Botkit .hears function.

**Comment by pgoldweic** [comment] 2018-10-29 15:30
A clarification question: are 'client' actions those supposed to be executed by the bot application? (I thought these were called 'app' actions, but this thread seems to imply this).

**Comment by data-henrik** [comment] 2018-10-29 15:42
https://console.bluemix.net/docs/services/conversation/dialog-actions.html#action-client-example

**Comment by Naktibalda** [comment] 2018-10-29 15:56
> @Naktibalda I have seen and worked with `sendToWatson`. My understanding is that it involves all the steps (before, after, etc.) again and it would introduce recursion. Basically, in the middle of processing `sendToWatson`, we call `sendToWatson` again.

That's how I used it.

**Comment by pgoldweic** [comment] 2018-10-29 15:59
OK. A year ago this full documentation wasn't there, so I imagine that lacking that specificity, this middleware simply enabled each user to implement their own 'client actions' using the documentation under 'app actions'. This is what I did, using their example, to implement simple 'client' actions that did not use parameters. Unfortunately this requires every developer to implement their own mechanism, which is not ideal, of course. It would be nice to have it already built into this middleware. I think this is what you are asking for @data-henrik, correct? I'm curious about the issue you describe with sendToWatson though; I've used it as exemplified in this middleware's docs (under 'app actions') and did not see a problem though.

**Comment by data-henrik** [comment] 2018-10-29 16:01
Correct, I am asking to have consistent documentation :)

**Comment by pgoldweic** [comment] 2018-10-29 16:16
It seems (and @Naktibalda appears to confirm this ) that it is *not* supporting this form of client actions yet. The only thing that it supports so far is using a mechanism exactly as described in the section 'Implementing app actions'. My understanding (and experience with it) is that you have to reproduce the 'processWatsonResponse' function as described there to have these simple actions (without parameters) work. This does in fact send the action results back to Watson in the manner described. However, in order to implement a more complex mechanism as explained in the documentation you pointed us to, somebody would have to code it first :-(. I agree that it would be great to have it.

**Comment by germanattanasio** [comment] 2018-11-18 19:02
This is a feature that we will have to discuss @mitchmason. Let me know what you think

**Comment by hendrul** [comment] 2018-11-30 19:51
Experimenting a little here I've written a botkit listener that do what [the only example](https://console.bluemix.net/docs/services/assistant/dialog-actions.html#section-action-client-example) of client actions I have seen so far suggest, (which is also incomplete by the way, as it doesn't send the result back ). 

> "The new POST message request should include the message returned by the previous POST message response (namely, the context, input, intents, entities, and optionally the output section) and, instead of the JSON object that defines the programmatic call to make, it should include the result that was returned from the programmatic call."

This is confusing and incomplete, because it says:
> Instead of the JSON object that defines the programmatic call

I assume they referred to each action descriptor in the actions array been replaced by the results

```js
var request = require("request");
var path = require("path");
var fs = require("fs");

var ACTIONS_DIR = "../actions/";
// prettier-ignore
var ASSISTANT_SENDMESSAGE_URL =
  `https://gateway.watsonplatform.net/assistant/api/v1/workspaces/${process.env.ASSISTANT_WORKSPACE_ID}/message`;

module.exports = function(controller, middleware) {
  controller.on(["message_received", "hello"], function(bot, message) {
    var watsonData = message.watsonData;
    if (watsonData && watsonData.actions) {
      var actionCalls = watsonData.actions;
      module.exports
        .executeActions(actionCalls, module.exports.actions)
        .then(function(results) {
          // Replace the action descriptor's in the original watson response object 
          // with the results as suggested
          var message = Object.assign({}, watsonData, { actions: results });
          var options = {
            auth: {
              user: process.env.ASSISTANT_USERNAME,
              pass: process.env.ASSISTANT_PASSWORD
            },
            url: ASSISTANT_SENDMESSAGE_URL,
            qs: { version: "2018-09-20" },
            body: message,
            json: true
          };
          request.post(options, function(error, response, body) {
            if (error) throw new Error(error);
            console.log(body);
          });
        });
    }
  });
};

/**
 * Runs actions sequentially, returning the list with the corresponding results, If there is any 
 * error during an action execution, add the error as result and stop the execution of other actions.
 * This is what this example bearly specifies:
 * https://console.bluemix.net/docs/services/assistant/dialog-actions.html#section-action-client-example
 */
module.exports.executeActions = function(actionCalls) {
  var results = [];
  var p = Promise.resolve();
  for (var i = 0; i < actionCalls.length; i++) {
    if (actionCalls[i].type === "client") {
      var actionCall = actionCalls[i];
      var actionParams = Object.assign({}, process.env, actionCall.parameters);
      p = p.then(function() {
        var action = findAction(actionCall.name);
        // prettier-ignore
        return Promise.resolve(action(actionParams))
          .then(results.push.bind(results))
      });
    }
  }
  return p
    .catch(function(err) {
      results.push({
        action_error: err.message
      });
    })
    .then(function() {
      return results;
    });
};

function findAction(name) {
  var normalizedPath = require("path").join(__dirname, ACTIONS_DIR, name);
  var action = require(normalizedPath);
  if (typeof action !== "function" && typeof action.main === "function") {
    action = action.main;
  }
  return action;
}
```
But it Doesn't works, I thought WA was going to recognize this protocol and it was going to add the results in the corresponding variable, which could be set on the context, input, or output attributes depending on the prefix.

> "If you want to save the result to the output or input section of the /message response, then you can prepend one of the following location keywords to the result_variable_name:
         output.: Adds the result to the output section of the /message response. For example, output.my_result.
         input.: Adds the result to the input section of the /message response. For example, input.my_result."

> "You can include periods in the variable name to create a nested JSON object. For example
         * context.weather.today
         * context.weather.tomorrow
"

And then in [Handling Errors](https://console.bluemix.net/docs/services/assistant/dialog-actions.html#handling-errors):
> "For a client type programmatic call, you can pass information about error processing by defining a context variable, such as action_error. You can pass it back to the service as part of the result variable. Then, you can display a response only if no errors were encountered by defining a response condition:"

I make a change sending in the body of the result's POST message, the merge of the original message and the object containing the results in their respective path.

```js
var set = require("lodash.set");
var merge = require("deepmerge");
var request = require("request");
var path = require("path");
var fs = require("fs");

var ACTIONS_DIR = "../actions/";
// prettier-ignore
var ASSISTANT_SENDMESSAGE_URL =
  `https://gateway.watsonplatform.net/assistant/api/v1/workspaces/${process.env.ASSISTANT_WORKSPACE_ID}/message`;

module.exports = function(controller, middleware) {
  controller.on(["message_received", "hello"], function(bot, message) {
    var watsonData = message.watsonData;
    if (watsonData && watsonData.actions) {
      var actionCalls = watsonData.actions;
      module.exports
        .executeActions(actionCalls, module.exports.actions)
        .then(function(result) {
          var options = {
            auth: {
              user: process.env.ASSISTANT_USERNAME,
              pass: process.env.ASSISTANT_PASSWORD
            },
            url: ASSISTANT_SENDMESSAGE_URL,
            qs: { version: "2018-09-20" },
            body: merge(watsonData, result),  //Merge
            json: true
          };
          request.post(options, function(error, response, body) {
            if (error) throw new Error(error);
            // Do something else!
          });
        });
    }
  });
};

module.exports.executeActions = function(actionCalls) {
  var result = { context: {} };
  var p = Promise.resolve();
  for (var i = 0; i < actionCalls.length; i++) {
    if (actionCalls[i].type === "client") {
      var actionCall = actionCalls[i];
      var actionParams = Object.assign({}, process.env, actionCall.parameters);
      p = p.then(function() {
        var action = findAction(actionCall.name);
        return Promise.resolve(action(actionParams)).then(function(
          actionResult
        ) {
          // set the result on it's respective path 
          if (/^(context|input|output)\./.test(actionCall.result_variable)) {
            set(result, actionCall.result_variable, actionResult);  
          } else {
            set(
              result.context,
              actionCall.result_variable.replace(/^\$/, ""),
              actionResult
            );
          }
          return;
        });
      });
    }
  }
  return p
    .then(function() {
      return result;
    })
    .catch(function(err) {
      return {
        context: {
          action_error: err.message
        }
      };
    });
};

function findAction(name) {
  var normalizedPath = require("path").join(__dirname, ACTIONS_DIR, name);
  var action = require(normalizedPath);
  if (typeof action !== "function" && typeof action.main === "function") {
    action = action.main;
  }
  return action;
}
``` 
 
This works

**Comment by HARVS1789UK** [comment] 2018-12-11 16:50
@hendrul thanks for sharing the above, I am hopeful based on @data-henrik's thumbs up that it is a potential solution. I have read through it myself and it looks to cover all the bases, but I am new to Node.js, ES6 style JS, new to Botkit and new to Watson Assistant!

I therefore have a few questions for you to help me attempt to implement your interim fix/wrapper:

1 - In which file would I place this code (app.js)?
2 - Am I correct in thinking that I would need to create a sub-directory in my web root named `acions` and create 1 x new .js file for each of my Watson Assistant 'Dialog Actions' (e.g. `../actions/getSuitableBusStops.js`)?
3 - Assuming #2 is correct, what form would these take? Would it be:
```js
module.exports = function(params) {
    // ...put my code here (params = the JSON params provided in WA 'action')...
}
```
4 - Are there any other steps I would have to implement to get it all to work other than the above?

@germanattanasio just as an FYI, massive +1 for some sort of listener for "watsonData contains action(s)" being built in functionality :-D

**Comment by hendrul** [comment] 2018-12-11 20:07
> In which file would I place this code (app.js)?

I'm using the [starter kit for botkit](https://github.com/howdyai/botkit-starter-web), this code is a "skill", which consist of a function which accept the botkit controller as a parameter, I modified the original caller to pass the watson middleware as second argument. That's my particular way to wrap "after".

> Am I correct in thinking that I would need to create a sub-directory in my web root named acions and create 1 x new .js file for each of my Watson Assistant 'Dialog Actions' (e.g. ../actions/getSuitableBusStops.js)?

> Assuming # 2 is correct, what form would these take? Would it be:

Yes, thats right, here is an example action:
```javascript
// actions/get-intents-description.js

var AssistantV1 = require("watson-developer-cloud/assistant/v1");

var cache;
function main(params) {
  var intentRegex = new RegExp(params["regex"] ? params["regex"] : ".*", "i");
  return new Promise(function(resolve, reject) {
    var currentTime = Date.now();
    if (cache && currentTime - cache.lastUpdate < 60 * 1000) {
      resolve(filterIntents(cache.data, intentRegex));
    } else {
      var conversation = new AssistantV1({
        username: params["ASSISTANT_USERNAME"],
        password: params["ASSISTANT_PASSWORD"],
        version: params["ASSISTANT_APIVERSION"],
        url: params["ASSISTANT_URL"]
      });
      conversation.listIntents(
        {
          workspace_id: params["ASSISTANT_WORKSPACE_ID"],
          export: true
        },
        function(err, response) {
          var descriptions = filterIntents(response.intents, intentRegex);
          cache = {
            lastUpdate: Date.now(),
            data: response.intents
          };
          resolve(descriptions);
        }
      );
    }
  });
}

function filterIntents(intents, regex) {
  return intents
    .filter(function(intent) {
      return (
        intent &&
        typeof intent.intent === "string" &&
        typeof intent.description === "string" &&
        intent.description.length > 0 &&
        !!intent.intent.match(regex)
      );
    })
    .map(function(intent) {
      return intent.description;
    });
}

module.exports = main;
``` 
And as you can see I'm accessing environment variables from the argument params

> Are there any other steps I would have to implement to get it all to work other than the above?

As a user wrapping after is the best choice I see to add this extension... but a contributor could add it built into sendToWatson or something more elaborated

**Comment by germanattanasio** [comment] 2019-04-28 20:56
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Closed by germanattanasio** 2019-04-28 20:56 UTC
Labels: feature, help wanted
